#!/sbin/busybox sh

# Remove links that busybox has
/sbin/busybox --list | while read line;
do
    if [[ "$line" == "reboot" ]]; then
	continue
    fi 
    /sbin/busybox rm /sbin/$line
done

# Install all busybox's links
/sbin/busybox --list | while read line;
do 
    if [[ "$line" == "reboot" ]]; then
	continue
    fi 
    /sbin/busybox ln -s /sbin/busybox /sbin/$line
done
