#!/sbin/busybox sh

BLOCK="/dev/block/platform/hi_mci.0/by-name"

mecho() {
	echo $1 >> /tmp/recovery.log
}

checkerror() {
    if [[ $1 -gt 0 ]]; then
	if [[ "$3" == "-fatal" ]]; then
		mecho "ERROR: $2"
		exit 9
	else
		mecho "WARNING: $2"	
	fi
    fi
}

mount() {
	if [[ $( cat /proc/mounts | grep -c $1) -gt 0 ]]; then
		mecho "$1 is already mounted.."
	else
		/sbin/mount -t ext4 $BLOCK$1 $1
		checkerror $? "Could not mount $1" $2
	fi
}

umount() {
	if [[ $( cat /proc/mounts | grep -c $1) -gt 0 ]]; then
		/sbin/umount $1
		checkerror $? "Could not umount $1" $2
	else
		mecho "$1 is already umounted.."
	fi
}

switch_fstab() {
	cp /etc/stock.twrp.fstab /etc/twrp.fstab
	checkerror $? "Could not overwrite stab!" -fatal
        cp /fstab.hi6250.stock /fstab.hi6250
	checkerror $? "Could not overwrite stab!" -fatal
}

is_cyanogen() {
	if [[ $( cat /system/build.prop | grep -c cm_hi6250) -gt 0 ]]; then
		mecho "Fstab Mode CyanogenMod"
	else
		mecho "Fstab Mode Stock"
		switch_fstab
		/sbin/setprop sys.stock 1
		/sbin/setprop ro.crypto.fs_crypto_blkdev /dev/block/dm-0
		/sbin/setprop ro.crypto.state encrypted
		/sbin/setprop ro.crypto.type block
		sed 's/0090CA/CA0026/g' < /twres/ui.xml > /twres/nui.xml
		cp /twres/nui.xml /twres/ui.xml
		sed 's/0090CA/CA0026/g' < /twres/splash.xml > /twres/nsplash.xml
		cp /twres/nsplash.xml /twres/splash.xml
	fi
}

mount /system -fatal
is_cyanogen
umount /system
